### ISSUE TITLE
Some improvements

### ISSUE THREAD

**Issue by igarrido-adalab** [Adalab/modulo-2-evaluacion-intermedia-BessyEscobar#1]
Really cool job @BessyEscobar !!!

Here you have some tips to complete the exercise:

### JavaScript: basic

- [ ] Execute `getRandomNumber` function when the page loads. Put the name of the function followed by two parenthesis () out of any other function. Before the function, in the same line, create a variable `randomNumber` to store the number that returns the function.
- [ ] Inside `handleClick` function, create a variable (named `userNumber`, for example) and store the value of the input in it (remember use parseInt to transform the value from a text number to a number number).
- [ ] Compare the user selection with the computer generated item and write the results into the page inside the `handleClick`.
- [ ] In the if's structure, first check for one option, then the other and then for the rest is enough with an `else` statement.
- [ ] Check if the user number is valid (with `isNaN()`).
- [ ] Check if the user number is into the valid range (0-100).
- [ ] Check if the random number is greater than the user number.
- [ ] Check if the random number is lower than the user number.
- [ ] Show a feedback message to the player for each condition.
- [ ] Show a feedback message to the player when she wins.
- [ ] Watch out for selector names used in `querySelector()` methods... they must exist in our HTML code!!
- [ ] Remove unnecessary code (like this <https://github.com/Adalab/modulo-2-evaluacion-intermedia-BessyEscobar/blob/59f23b6cdf68e0ed67970d12e1fefce7530bdd5c/JS/main.js#L33-L35>)

### JavaScript: advanced

- [ ] Use a global variable to store the tries counter of the player, increment it and refresh the HTML using that variable.
- [ ] Move the feedback logic to a function and execute it on each click.
- [ ] Move your counter of tries logic into a function and execute it on each click.
- [ ] You are writing many times `"clueEl.innerHTML = 'something';"`, what about making a function that accepts a string as param and paints it into `'clueEl'`?

### Good practices

- [ ] Remove unnecessary commented code before commit.
- [ ] Make multiple commits as you work. 
- [ ] Try to improve your commits messages. "Add JS" is a bit poor. "Add random number logic" is more explanatory.

### HTML

- [ ] Add form

### CSS

- [ ] Avoid adding styles until the js code is solid as a rock.

### Call to action

Let me know if you have any doubts ;)

Go for it!!

> From now on you can commit your changes to the main branch of your project.
> Do not close this issue until your teacher asks you to

**Comment by BessyEscobar** [comment]
Thanks for your comment, I have implemented the suggestions in the dev branch.
